"""Safe CI configuration generation for Git-backed Beacon projects."""
from __future__ import annotations

import json
import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .cli_runner import CliProjectError, shell_variable_name
from .services.project_file_sync import SECRET_NAME


DEFAULT_WORKFLOW = Path(".github/workflows/beacon.yml")


@dataclass(frozen=True)
class GithubWorkflowPlan:
    repository_root: Path
    project_root: Path
    project_path: str
    destination: Path
    environment_name: str | None
    secret_names: tuple[str, ...]
    content: str


@dataclass(frozen=True)
class GithubWorkflowWriteResult:
    path: Path
    state: str


def find_repository_root(project_root: Path, explicit_root: str | Path | None = None) -> Path:
    project_root = project_root.resolve()
    if explicit_root is not None:
        candidate = Path(explicit_root).expanduser().resolve()
        if not (candidate / ".git").exists():
            raise CliProjectError(f"Git repository not found at {candidate}")
        try:
            project_root.relative_to(candidate)
        except ValueError as error:
            raise CliProjectError("Beacon project must be inside the selected Git repository") from error
        return candidate

    for candidate in (project_root, *project_root.parents):
        if (candidate / ".git").exists():
            return candidate
    raise CliProjectError(
        "No Git repository contains this Beacon project. Run git init or use --repo-root PATH."
    )


def discover_github_secrets(environment: dict[str, Any] | None) -> tuple[str, ...]:
    variables = (environment or {}).get("variables") or {}
    names: dict[str, str] = {}
    for variable_name in variables:
        source_name = str(variable_name)
        if not SECRET_NAME.search(source_name):
            continue
        github_name = f"BEACON_VAR_{shell_variable_name(source_name)}"
        if github_name in names and names[github_name] != source_name:
            raise CliProjectError(
                f"Private variables {names[github_name]!r} and {source_name!r} both map to {github_name}. "
                "Rename one variable before generating CI."
            )
        names[github_name] = source_name
    return tuple(sorted(names))


def create_github_workflow_plan(
    project_root: Path,
    project: dict[str, Any],
    environment: dict[str, Any] | None,
    *,
    cli_version: str,
    repository_root: str | Path | None = None,
) -> GithubWorkflowPlan:
    repo_root = find_repository_root(project_root, repository_root)
    relative = project_root.resolve().relative_to(repo_root)
    project_path = relative.as_posix() or "."
    secret_names = discover_github_secrets(environment)
    environment_name = str(environment.get("name")) if environment else None
    destination = repo_root / DEFAULT_WORKFLOW
    return GithubWorkflowPlan(
        repository_root=repo_root,
        project_root=project_root.resolve(),
        project_path=project_path,
        destination=destination,
        environment_name=environment_name,
        secret_names=secret_names,
        content=render_github_workflow(
            project_name=str(project.get("name") or "Beacon project"),
            project_path=project_path,
            environment_name=environment_name,
            secret_names=secret_names,
            cli_version=cli_version,
        ),
    )


def render_github_workflow(
    *,
    project_name: str,
    project_path: str,
    environment_name: str | None,
    secret_names: tuple[str, ...],
    cli_version: str,
) -> str:
    normalized_version = str(cli_version or "").strip().removeprefix("v")
    if normalized_version != "latest" and not re.fullmatch(
        r"\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?",
        normalized_version,
    ):
        raise CliProjectError("CLI version must be a semantic version such as 0.4.8, or 'latest'")
    release_segment = "latest/download" if normalized_version == "latest" else f"download/v{normalized_version}"
    env_lines = [f"      BEACON_PROJECT: {json.dumps(project_path)}"]
    if environment_name:
        env_lines.append(f"      BEACON_ENV: {json.dumps(environment_name)}")
    env_lines.extend(f"      {name}: ${{{{ secrets.{name} }}}}" for name in secret_names)
    env_block = "\n".join(env_lines)
    env_arg = ' --env "$BEACON_ENV"' if environment_name else ""
    display_name = project_name.replace("\r", " ").replace("\n", " ").strip() or "Beacon project"
    return f"""# Generated by Beacon CLI for {display_name}
name: Beacon API tests

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  api-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
{env_block}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Beacon CLI
        shell: bash
        run: |
          curl --fail --silent --show-error --location \\
            https://github.com/nannndev/beacon/releases/{release_segment}/beacon-linux-x64 \\
            --output "$RUNNER_TEMP/beacon"
          chmod +x "$RUNNER_TEMP/beacon"
          echo "$RUNNER_TEMP" >> "$GITHUB_PATH"

      - name: Validate Beacon project
        shell: bash
        run: beacon validate "$BEACON_PROJECT"{env_arg} --strict

      - name: Run Beacon project
        shell: bash
        run: |
          beacon run "$BEACON_PROJECT"{env_arg} --bail --quiet --github \\
            --report-junit "$BEACON_PROJECT/reports/beacon.xml" \\
            --report-json "$BEACON_PROJECT/reports/beacon.json"

      - name: Upload Beacon reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: beacon-reports
          path: ${{{{ env.BEACON_PROJECT }}}}/reports/
          if-no-files-found: ignore
"""


def write_github_workflow(plan: GithubWorkflowPlan, *, force: bool = False) -> GithubWorkflowWriteResult:
    target = plan.destination
    existed = target.exists()
    if existed:
        try:
            existing = target.read_text(encoding="utf-8")
        except OSError as error:
            raise CliProjectError(f"Could not read existing workflow: {error}") from error
        if existing == plan.content:
            return GithubWorkflowWriteResult(path=target, state="unchanged")
        if not force:
            raise CliProjectError(
                f"Workflow already exists at {target}. Review with --dry-run, then use --force to replace it."
            )

    target.parent.mkdir(parents=True, exist_ok=True)
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=target.parent,
            prefix=".beacon-workflow-",
            suffix=".tmp",
            delete=False,
        ) as handle:
            handle.write(plan.content)
            temporary_name = handle.name
        os.replace(temporary_name, target)
    except OSError as error:
        if temporary_name:
            Path(temporary_name).unlink(missing_ok=True)
        raise CliProjectError(f"Could not write GitHub Actions workflow: {error}") from error
    return GithubWorkflowWriteResult(path=target, state="updated" if existed else "created")
